//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmes1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CatalogoFilmes
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "O campo não pode estar em branco."), Display(Name = "Título")]
        public string Titulo { get; set; }
        [DataType(DataType.Time)]
        public string Duracao { get; set; }
        [StringLength(4), Range(1, Double.PositiveInfinity)]
        public string Ano { get; set; }
        [Required(ErrorMessage = "O campo não pode estar em branco."), Display(Name = "Tipo de Mídia")]
        public string TipoMidia { get; set; }
        public string Elenco { get; set; }
        [Display(Name = "Direção")]
        public string Direcao { get; set; }
    }
}
